### ISSUE TITLE
bgpd coredump while peer down

### ISSUE THREAD

**Issue by richard28530** [sonic-net/sonic-quagga#23] opened 2018-07-26 03:19 UTC
I has 3 switch running the same version SONiC/quagga.

Topology as below，each switch connect to spine with two layer 3 link which establish EBGP neighbor.
<pre>
                          Spine
                    /  /          \ \ 
             Leaf Left        Leaf Right
</pre>

What I do is update software version of spine, reboot the switch several times.
Then I found the bgpd of quagga coredump. the coredump info as below.

<pre>
    Jul 19 02:52:01.662427 S9130-Leaf-Left INFO bgpd[57]: %NOTIFICATION: sent to neighbor 10.10.116.26 6/3 (Cease/Peer Unconfigured) 0 bytes
    Jul 19 02:52:01.662427 S9130-Leaf-Left INFO bgpd[57]: Notification sent to neighbor 10.10.116.26: type 6/3
    Jul 19 02:52:01.662479 S9130-Leaf-Left INFO bgpd[57]: %NOTIFICATION: sent to neighbor 10.10.117.26 6/3 (Cease/Peer Unconfigured) 0 bytes
    Jul 19 02:52:01.662479 S9130-Leaf-Left INFO bgpd[57]: Notification sent to neighbor 10.10.117.26: type 6/3
    Jul 19 02:52:01.662523 S9130-Leaf-Left INFO bgpd[57]: %NOTIFICATION: sent to neighbor 10.10.116.26 6/2 (Cease/Administratively Shutdown) 0 bytes
    Jul 19 02:52:01.662523 S9130-Leaf-Left INFO bgpd[57]: Notification sent to neighbor 10.10.116.26: shutdown
    Jul 19 02:52:01.662523 S9130-Leaf-Left INFO bgpd[57]: %ADJCHANGE: neighbor 10.10.116.26 Down Neighbor deleted
    Jul 19 02:52:01.662581 S9130-Leaf-Left INFO bgpd[57]: %NOTIFICATION: sent to neighbor 10.10.117.26 6/2 (Cease/Administratively Shutdown) 0 bytes
    Jul 19 02:52:01.662581 S9130-Leaf-Left INFO bgpd[57]: Notification sent to neighbor 10.10.117.26: shutdown
    Jul 19 02:52:01.662593 S9130-Leaf-Left INFO bgpd[57]: %ADJCHANGE: neighbor 10.10.117.26 Down Neighbor deleted
    Jul 19 02:52:10.412298 S9130-Leaf-Left NOTICE bgpd[56]: BGPd 0.99.24.1 starting: vty@2605, bgp@<all>:179
    Jul 19 02:52:31.706505 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.117.26 Up
    Jul 19 02:54:06.693167 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.116.26 Up
    Jul 23 01:29:33.253106 S9130-Leaf-Left INFO bgpd[56]: %NOTIFICATION: received from neighbor 10.10.117.26 6/3 (Cease/Peer Unconfigured) 0 bytes
    Jul 23 01:29:33.253106 S9130-Leaf-Left INFO bgpd[56]: %NOTIFICATION: received from neighbor 10.10.116.26 6/3 (Cease/Peer Unconfigured) 0 bytes
    Jul 23 01:29:33.253106 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.117.26 Down BGP Notification received
    Jul 23 01:29:33.253191 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.116.26 Down BGP Notification received
    Jul 23 02:49:06.024443 S9130-Leaf-Left NOTICE bgpd[56]: BGPd 0.99.24.1 starting: vty@2605, bgp@<all>:179
    Jul 23 12:40:06.358609 S9130-Leaf-Left INFO bgpd[56]: %NOTIFICATION: sent to neighbor 10.10.117.26 6/7 (Cease/Connection collision resolution) 0 bytes
    Jul 23 12:40:06.358609 S9130-Leaf-Left INFO bgpd[56]: Notification sent to neighbor 10.10.117.26: type 6/7
    Jul 23 12:40:06.358663 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.117.26 Up
    Jul 23 12:40:07.357840 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.116.26 Up
    Jul 24 07:21:42.081717 S9130-Leaf-Left INFO bgpd[56]: %NOTIFICATION: received from neighbor 10.10.116.26 6/3 (Cease/Peer Unconfigured) 0 bytes
    Jul 24 07:21:42.081717 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.116.26 Down BGP Notification received
    Jul 24 07:21:42.081717 S9130-Leaf-Left INFO bgpd[56]: %NOTIFICATION: received from neighbor 10.10.117.26 6/3 (Cease/Peer Unconfigured) 0 bytes
    Jul 24 07:21:42.081717 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.117.26 Down BGP Notification received
    Jul 24 07:45:45.029799 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.116.26 Up
    Jul 24 07:45:53.163284 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.117.26 Up
    Jul 24 11:21:25.797877 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.117.26 Down NSF peer closed the session
    Jul 24 11:21:25.797877 S9130-Leaf-Left INFO bgpd[56]: %ADJCHANGE: neighbor 10.10.116.26 Down NSF peer closed the session
    Jul 24 11:22:10.170495 S9130-Leaf-Left CRIT bgpd[56]: Received signal 11 at 1532431330 (si_addr 0x0, PC 0x7fd8be671080); aborting...
    Jul 24 11:22:10.171797 S9130-Leaf-Left CRIT bgpd[56]: Backtrace for 13 stack frames:
    Jul 24 11:22:10.172280 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/libzebra.so.0(zlog_backtrace_sigsafe+0x42) [0x7fd8be680d22]
    Jul 24 11:22:10.172280 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/libzebra.so.0(zlog_signal+0x30c) [0x7fd8be68146c]
    Jul 24 11:22:10.172280 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/libzebra.so.0(+0x3d74f) [0x7fd8be68b74f]
    Jul 24 11:22:10.172280 S9130-Leaf-Left CRIT bgpd[56]: /lib/x86_64-linux-gnu/libc.so.6(+0x350e0) [0x7fd8bd9930e0]
    Jul 24 11:22:10.172306 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/libzebra.so.0(sockunion_cmp+0) [0x7fd8be671080]
    Jul 24 11:22:10.172306 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/quagga/bgpd(+0x49512) [0x5563f7c3b512]
    Jul 24 11:22:10.172306 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/quagga/bgpd(+0x49b7a) [0x5563f7c3bb7a]
    Jul 24 11:22:10.172321 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/quagga/bgpd(+0x49f7e) [0x5563f7c3bf7e]
    Jul 24 11:22:10.172321 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/libzebra.so.0(work_queue_run+0xe7) [0x7fd8be68c337]
    Jul 24 11:22:10.172333 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/libzebra.so.0(thread_call+0x6c) [0x7fd8be673efc]
    Jul 24 11:22:10.172333 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/quagga/bgpd(main+0x380) [0x5563f7c20900]
    Jul 24 11:22:10.172346 S9130-Leaf-Left CRIT bgpd[56]: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fd8bd97fb45]
    Jul 24 11:22:10.172346 S9130-Leaf-Left CRIT bgpd[56]: /usr/lib/quagga/bgpd(+0x2e998) [0x5563f7c20998]
    Jul 24 11:22:10.172387 S9130-Leaf-Left CRIT bgpd[56]: read work_queue_run scheduled from workqueue.c:119

    root@S9130-Leaf-Left:/# gdb /usr/lib/quagga/bgpd bgpd.1532431330.56.core
    GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from /usr/lib/quagga/bgpd...Reading symbols from /usr/lib/debug//usr/lib/quagga/bgpd...done.
    done.
    [New LWP 56]
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    Core was generated by `/usr/lib/quagga/bgpd -A 127.0.0.1 -F'.
    Program terminated with signal SIGABRT, Aborted.
    #0  0x00007fd8bd993067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
        56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
        (gdb) bt
    #0  0x00007fd8bd993067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
    #1  0x00007fd8bd994448 in __GI_abort () at abort.c:89
    #2  0x00007fd8be68b754 in core_handler (signo=<optimized out>, siginfo=<optimized out>, context=<optimized out>) at sigevent.c:240
    #3  <signal handler called>
    #4  sockunion_cmp (su1=0x0, su2=0x0) at sockunion.c:730
    #5  0x00005563f7c3b512 in bgp_info_cmp (bgp=bgp@entry=0x5563f9398350, new=new@entry=0x5563f93b8a70, exist=exist@entry=0x5563f93a56f0, paths_eq=paths_eq@entry=0x7fff3d36858c) at bgp_route.c:556
    #6  0x00005563f7c3bb7a in bgp_best_selection (bgp=bgp@entry=0x5563f9398350, rn=rn@entry=0x5563f93a3510, mpath_cfg=mpath_cfg@entry=0x5563f9398918, result=result@entry=0x7fff3d368610) at bgp_route.c:1408
    #7  0x00005563f7c3bf7e in bgp_process_main (wq=<optimized out>, data=<optimized out>) at bgp_route.c:1577
    #8  0x00007fd8be68c337 in work_queue_run (thread=0x7fff3d368850) at workqueue.c:293
    #9  0x00007fd8be673efc in thread_call (thread=0x7fff3d368850) at thread.c:1252
    #10 0x00005563f7c20900 in main (argc=4, argv=<optimized out>) at bgp_main.c:473
    (gdb) quit
    root@S9130-Leaf-Left:/# exit
    exit
</pre>

**Comment by paulnice** [comment] 2019-03-08 03:47
Hi Richard,

Can you reproduce the issue?
It looks like bgpd started best path selection process with both peers in down state. Right?
I you can reproduce the issue - can you please send me a coredump?

Thanks

**Comment by richard28530** [comment] 2019-03-17 09:00
Hi,

this issue is reproducible(with several core file with the same calling stacking), but I not that familiar with routing code, so I switch this routing stack to frr instead which doesn't have the issue.

currently I not woking on SONiC, so I have no machine to reproduce the issue.

**Comment by pavel-shirshov** [comment] 2019-07-12 00:00
Fixed in https://github.com/Azure/sonic-quagga/commit/99d9ca8e3291cead8a3f15ff2cb15cf53d70a896

**Closed as completed by pavel-shirshov** 2019-07-12 00:00 UTC
Labels: bug, critical
